const projects = [
  {
    id: 1,
    title: "한국닌텐도",
    subTitle: "한국닌텐도 소개 및 판매",
    summary: "구조 재설계 UI/UX 프로젝트",
    description: "사용자 경험을 중심으로 정보 위계를 재정리하고,퍼블리싱 관점에서 완성도 높은 UI 구현을 목표로 함",
    thumb: "images/thumb03.png",
    stack: ["SCSS", "JavaScript"],
    type: "팀",
    period: "2026.01 ~ 2026.02",
    tags: ["scss", "js", "responsive", "recent"],
    img: "images/project-img03.svg",
    stack: [
      { name: "html", icon: "images/skill-icon01.png" },
      { name: "scss", icon: "images/skill-icon03.png" },
      { name: "javascript", icon: "images/skill-icon04.png" },
      { name: "swiper", icon: "images/skill-icon08.png" },
      { name: "vscode", icon: "images/skill-icon09.png" },
      { name: "figma", icon: "images/skill-icon11.png" },
      { name: "photoshop", icon: "images/skill-icon12.png" },
      { name: "ai", icon: "images/skill-icon13.png" }
    ],
    ppt: "https://www.figma.com/deck/6irwv1qNXooL2BzOl1OsOT",
    site: "https://zhaeees.github.io/Nintendo-Renewal/",
    github: "https://github.com/zhaeees/Nintendo-Renewal",
    figma: "https://www.figma.com/design/SsP6DWrFjImVIl5autmaDN/%EC%97%90%EC%8A%A4%ED%8C%8C-%EB%8B%8C%ED%85%90%EB%8F%84%EB%A6%AC%EB%89%B4%EC%96%BC?node-id=0-1&t=1EGCoIr7S4DjklFw-1"
  },
  {
    id: 2,
    title: "테디테일즈",
    subTitle: "테디테일즈 인형 판매 ",
    summary: "인형 쇼핑몰 사이트 리디자인",
    description: "모바일 중심 UI 개선과 구매 전환율 향상을 목표로 한 쇼핑몰 리디자인 프로젝트",
    thumb: "images/thumb02.svg",
    stack: ["SCSS", "JavaScript"],
    type: "개인",
    period: "2026.01 ~ 2026.01",
    tags: ["scss", "js", "responsive", "recent"],
    img: "images/project-img02.svg",
     stack: [
      { name: "html", icon: "images/skill-icon01.png" },
      { name: "scss", icon: "images/skill-icon03.png" },
      { name: "javascript", icon: "images/skill-icon04.png" },
      { name: "swiper", icon: "images/skill-icon08.png" },
      { name: "vscode", icon: "images/skill-icon09.png" },
      { name: "figma", icon: "images/skill-icon11.png" },
      { name: "photoshop", icon: "images/skill-icon12.png" },
      { name: "ai", icon: "images/skill-icon13.png" }
    ],
    ppt: "",
    site: "",
    github: "",
    figma: ""
  },
  {
    id: 3,
    title: "한국공항공사",
    subTitle: "공항안내 및 항공사 소개",
    summary: "직관적인 정보 전달을 위한 웹 리디자인",
    description: "본 리뉴얼은 정보 구조 단순화와 사용자 동선 개선을 통해 핵심 콘텐츠 접근성을 높이는 것을 목표로 함.",
    thumb: "images/thumb01.png",
    stack: ["CSS", "JavaScript"],
    type: "개인",
    period: "2025.10 ~ 2025.11",
    tags: ["css", "js", "responsive", "recent"],
    img: "images/project-img01.svg",
     stack: [
      { name: "html", icon: "images/skill-icon01.png" },
      { name: "css", icon: "images/skill-icon02.png" },
      { name: "javascript", icon: "images/skill-icon04.png" },
      { name: "api", icon: "images/skill-icon06.png" },
      { name: "swiper", icon: "images/skill-icon08.png" },
      { name: "vscode", icon: "images/skill-icon09.png" },
      { name: "figma", icon: "images/skill-icon11.png" },
      { name: "photoshop", icon: "images/skill-icon12.png" },
      { name: "ai", icon: "images/skill-icon13.png" }
    ],
    ppt: "https://www.figma.com/deck/WlfXol5i5hcYz3tifUCk7B",
    site: "https://zhaeees.github.io/koreanairport-Renewal/",
    github: "https://github.com/zhaeees/koreanairport-Renewal",
    figma: "https://www.figma.com/design/vWrPlSnYOOtSFLhJWrxSbt/%ED%95%9C%EA%B5%AD%EA%B3%B5%ED%95%AD%EA%B3%B5%EC%82%AC-%EB%A6%AC%EB%89%B4%EC%96%BC_%EC%B5%9C%EC%A7%80%ED%98%9C?node-id=0-1&t=YsvKObIgYOundxuE-1"
  }
];